spring:
  datasource:
  jpa:
    properties:
      hibernate:
        default_schema: heroku_f8c10a0dcaaf757
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  main:
    allow-bean-definition-overriding: true

  output:
    ansi:
      enabled: ALWAYS

game-rules:
  starting-cash: 100000
  payoutMap:
    1: $200 Cash
    2: $100 Cash
    3: $20 Giftcard
    4: $20 Giftcard
    5: $20 Giftcard
    6: $20 Giftcard
    7: $20 Giftcard
    8: $20 Giftcard
    9: $20 Giftcard
    10: $20 Giftcard
  leaderboard:
    displayamount: 15

paypal:
  clientId: ${PAYPAL_CLIENTID}
  donationAmount: 5

admins: bradenborman@hotmail.com, bradenborman00@gmail.com
