spring:
  jpa:
    properties:
      hibernate:
        default_schema: heroku_f8c10a0dcaaf757
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          port: 25
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
        transport:
          protocol: smtp
  main:
    allow-bean-definition-overriding: true

  output:
    ansi:
      enabled: ALWAYS

game-rules:
  starting-cash: 100000

admins: bradenborman@hotmail.com, bradenborman00@gmail.com

sports-data-api:
  url: https://api.sportsdata.io/v3/cbb/scores/json/teams?key=df57fbe761424db78e5c16a103ceb0d0