spring:
  jpa:
    properties:
      hibernate:
        default_schema: heroku_f8c10a0dcaaf757

  main:
    allow-bean-definition-overriding: true

  output:
    ansi:
      enabled: ALWAYS

game-rules:
  starting-cash: 100000