spring:
  profiles:
    active: local

  main:
    allow-bean-definition-overriding: true

  output:
    ansi:
      enabled: ALWAYS

game-rules:
  starting-cash: 100000

sports-data-api:
  url: https://api.sportsdata.io/v3/cbb/scores/json/teams?key=df57fbe761424db78e5c16a103ceb0d0