spring:
  datasource:
#    testOnBorrow: true
#    maxActive: 5
#    testWhileIdle: true
#    timeBetweenEvictionRunsMillis: 60000
#    validationQuery: SELECT 1
#    tomcat:
#      testWhileIdle: true
#      timeBetweenEvictionRunsMillis: 60000
#      validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        default_schema: heroku_f8c10a0dcaaf757
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  main:
    allow-bean-definition-overriding: true

  output:
    ansi:
      enabled: ALWAYS

sports-data-api:
  url: https://api.sportsdata.io/v3/cbb/scores/json/teams?key=df57fbe761424db78e5c16a103ceb0d0

game-rules:
  starting-cash: 100000
  payoutMap:
    1: $200
    2: $100
    3: $50
    4: $20 Giftcard
    5: $20 Giftcard
    6: $20 Giftcard
    7: $20 Giftcard
    8: $20 Giftcard
    9: $20 Giftcard
    10: $20 Giftcard
  leaderboard:
    displayamount: 15

admins: bradenborman@hotmail.com, bradenborman00@gmail.com
