twilio:
  auth: ${Twilio_Auth}
  accountSsd: ${Twilio_ACCOUNT_SID}

sport-data-api:
  apiKey: ${SportsDataApiKey}
  url: https://api.sportsdata.io/v3/cbb/scores/json/teams?key=${sport-data-api.apiKey}

spring:
  thymeleaf:
    prefix: classpath:/static/
  jpa:
    properties:
      hibernate:
        default_schema: heroku_f8c10a0dcaaf757
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  main:
    allow-bean-definition-overriding: true

game-rules:
  starting-cash: 100000
  starting-price-per-share: 5000
  payoutMap:
    1: $200 Value
    2: $100 Value
    3: $20 Value
    4: $20 Value
    5: $20 Value
    6: $20 Value
    7: $20 Value
    8: $20 Value
    9: $20 Value
    10: $20 Value
  leaderboard:
    displayamount: 25

paypal:
  clientId: ${PAYPAL_CLIENTID}
  donationAmount: 10

admins: bradenborman@hotmail.com, bradenborman00@gmail.com
